# ~~~ database service ~~~
#
#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
#          |          |
#       __ |  __   __ | _  __   _
#      /  \| /  \ /   |/  / _\ |
#      \__/| \__/ \__ |\_ \__  |
#
# ~~~ mongo database ~~~

version: '3.1'

networks:
  local_net:
    external:
      name: local

volumes:
  dbdata:
    driver: local

services:
  apps:
    # restart: always
    container_name: apps
    image: kankuu/node-express:alpha
    user: node
    working_dir: /home/node/app
    external_links:
      - redis:redis
    volumes:
      - ./app:/home/node/app
    ports:
      - 80:3000
    networks:
      - local_net
    command: node index.js