#
#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
#          |          |
#       __ |  __   __ | _  __   _
#      /  \| /  \ /   |/  / _\ |
#      \__/| \__/ \__ |\_ \__  |
#

version: "3"

networks:
  local_net: 
    external:
      name: local 

volumes:
  dbdata:
    driver: local

services:
# Application Container
  apps:
    build:
      context: ./
      dockerfile: webapps.dockerfile
    container_name: apps
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # - ./mount/to/storage:/var/www/storage
    networks:
      - local_net
#    external_links:
#      - database:database
    environment:
      - "DB_PORT=docker_database_port" # default 3306
      - "DB_HOST=docker_database_host" # like an database compose is mysql-database

# Web Server Container
  apps-ws:
    build:
      context: ./
      dockerfile: webserver.dockerfile
    container_name: apps-ws
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /mount/to/storage:/var/www/storage
    ports:
      - "expose_port:80"
    networks:
      - local_net
