# ~~~ apps service ~~~
#
#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
#          |          |
#       __ |  __   __ | _  __   _
#      /  \| /  \ /   |/  / _\ |
#      \__/| \__/ \__ |\_ \__  |
#
# ~~~ netdata ~~~

version: "3"

networks:
  local_net: 
    external:
      name: local

volumes:
  dbdata:
    driver: local

services:
  netdata-monit:
    restart: always
    image: netdata/netdata
    container_name: netdata-monit
    networks:
      - local_net
    ports:
      - expose_port:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - apparmor=unconfined
    cap_add: 
      - SYS_PTRACE